module.exports = {
  apps: [
    {
      name: 'stock-radar',
      script: 'uv',
      args: 'run python src/main.py',
      cwd: '/root/work/stock-radar',
      interpreter: 'none',
      instances: 1,
      autorestart: false,
      cron_restart: '0 6 * * 6',
      watch: false,
      max_memory_restart: '512M',
      log_file: '/root/work/plusefin-landing-page/stock-radar/logs/radar.log',
      out_file: '/root/work/plusefin-landing-page/stock-radar/logs/radar-out.log',
      error_file: '/root/work/plusefin-landing-page/stock-radar/logs/radar-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'exec-trade',
      script: 'uv',
      args: 'run python exec_entry.py',
      cwd: '/root/work/stock-radar',
      interpreter: 'none',
      instances: 1,
      autorestart: false,
      cron_restart: '30 13 * * 1',  // Mon 13:30 UTC = 21:30 Beijing (夏令时覆盖); 冬令时自动sleep
      watch: false,
      max_memory_restart: '512M',
      log_file: '/root/work/plusefin-landing-page/stock-radar/logs/trade.log',
      out_file: '/root/work/plusefin-landing-page/stock-radar/logs/trade-out.log',
      error_file: '/root/work/plusefin-landing-page/stock-radar/logs/trade-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'gen-strategy',
      script: 'uv',
      args: 'run python src/strategy.py',
      cwd: '/root/work/stock-radar',
      interpreter: 'none',
      instances: 1,
      autorestart: false,
      cron_restart: '0 6 * * 6',   // Sat 06:00 UTC = Sat 14:00 Beijing (与雷达同步)
      watch: false,
      max_memory_restart: '512M',
      log_file: '/root/work/plusefin-landing-page/stock-radar/logs/strategy.log',
      out_file: '/root/work/plusefin-landing-page/stock-radar/logs/strategy-out.log',
      error_file: '/root/work/plusefin-landing-page/stock-radar/logs/strategy-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'export-site-strategy',
      script: 'bash',
      args: ['-lc', 'uv run python -m src.site_export strategy && bash scripts/publish_site.sh "chore: update public strategy page"'],
      cwd: '/root/work/stock-radar',
      interpreter: 'none',
      instances: 1,
      autorestart: false,
      cron_restart: '15 6 * * 6',   // Sat 06:15 UTC, after gen-strategy
      watch: false,
      max_memory_restart: '512M',
      log_file: '/root/work/plusefin-landing-page/stock-radar/logs/site-strategy.log',
      out_file: '/root/work/plusefin-landing-page/stock-radar/logs/site-strategy-out.log',
      error_file: '/root/work/plusefin-landing-page/stock-radar/logs/site-strategy-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
    {
      name: 'export-site-live',
      script: 'bash',
      args: ['-lc', 'uv run python -m src.site_export live --config config.yaml --initial-capital 22803.36 && bash scripts/publish_site.sh "chore: update public live account"'],
      cwd: '/root/work/stock-radar',
      interpreter: 'none',
      instances: 1,
      autorestart: false,
      cron_restart: '50 13 * * 1',  // Mon 13:50 UTC, after exec-trade
      watch: false,
      max_memory_restart: '512M',
      log_file: '/root/work/plusefin-landing-page/stock-radar/logs/site-live.log',
      out_file: '/root/work/plusefin-landing-page/stock-radar/logs/site-live-out.log',
      error_file: '/root/work/plusefin-landing-page/stock-radar/logs/site-live-error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
    },
  ]
};
